# .platform.app.yaml

name: 'drupal'
type: 'php:8.3'

relationships:
  database: 'db:mysql'
  redis: 'cache:redis'

disk: 2048

mounts:
  '/web/sites/default/files':
    source: local
    source_path: 'files'
  '/tmp':
    source: local
    source_path: 'tmp'
  '/private':
    source: local
    source_path: 'private'
  '/.drush':
    source: local
    source_path: 'drush'
  '/drush-backups':
    source: local
    source_path: 'drush-backups'
  '/private/config':
    source: local
    source_path: 'config'

build:
  flavor: composer

hooks:
  build: |
    set -e
    if [ -f .platform/.environment ]; then
      . .platform/.environment
    fi
    chmod +x drush/platformsh_deploy_drupal.sh
    chmod +x scripts/*.sh

  deploy: |
    set -e

    # Make sure environment is sourced
    if [ -f .platform/.environment ]; then
      . .platform/.environment
    fi

    echo "🚀 Generating Drush config..."
    php ./drush/platformsh_generate_drush_yml.php

    echo "📂 Checking config sync directory:"
    ls -alh /app/private/config/sync || echo "Not found"

    echo "🧼 Sanitizing UUIDs..."
    find /app/private/config/sync -type f -exec sed -i 's/^uuid: .*/uuid: /' {} \;

    echo "📥 Running config import with Drush..."
    php vendor/bin/drush config-import --source=/app/private/config/sync -y

    echo "▶️ Running platformsh_deploy_drupal.sh..."
    chmod +x drush/platformsh_deploy_drupal.sh
    ./drush/platformsh_deploy_drupal.sh



web:
  locations:
    '/':
      root: 'web'
      expires: 5m
      passthru: '/index.php'
      allow: false
      rules:
        '\.(avif|webp|jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
          allow: true
        '^/robots\.txt$':
          allow: true
        '^/sitemap\.xml$':
          allow: true
        '^/sites/sites\.php$':
          scripts: false
        '^/sites/[^/]+/settings.*?\.php$':
          scripts: false

    '/sites/default/files':
      allow: true
      expires: 5m
      passthru: '/index.php'
      root: 'web/sites/default/files'
      scripts: false
      rules:
        '^/sites/default/files/(css|js)':
          expires: 2w

crons:
  drupal:
    spec: '*/19 * * * *'
    commands:
      start: 'cd web && ../vendor/bin/drush core-cron'

runtime:
  extensions:
    - redis
    - sodium
    - apcu
    - blackfire

dependencies:
  php:
    composer/composer: "^2.7.0"
